data:
  - 'changelog*'
  - 'copyright*'
  - credits.txt
  - icon.png
  - keys.txt
  - license.txt
  - 'data/**/*'
  - 'images/**/*'
  - 'sounds/**/*'

game_code:
  - 'source/**'
  - 'tests/unit/**/*.h'
  - 'tests/unit/**/*.hpp'
  - 'tests/unit/**/*.cpp'

cmake:
  - CMakeLists.txt
  - source/CMakeLists.txt
  - tests/unit/CMakeLists.txt
  - CMakePresets.json
  - vcpkg/
  - vcpkg.json

integration_tests:
  - 'tests/integration/run_tests*'
  - 'data/tests/**'
  - 'tests/integration/universes/**'

parse_script:
  - 'utils/test_parse.*'

codespell:
  - .codespell.exclude

xcode_files:
  - 'EndlessSky.xcodeproj/**'
  - 'utils/check_xcode.sh'

codeblocks_files:
  - '*.cbp'
  - 'utils/check_codeblocks.sh'

copyright:
  - 'copyright'
