services:
  endless-sky-x64:
    image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    volumes:
      - '.:/endless-sky'
    working_dir: /endless-sky
    command:
      - '/bin/bash'
      - '-c'
      - |
        mkdir -p build/steam-x64
        cd build/steam-x64
        cmake ../../ -GNinja -DES_STEAM=ON -DES_RELEASE=ON -DCMAKE_BUILD_TYPE=Release
        ninja EndlessSky EndlessSkyTests
        ./endless-sky --version
        ./endless-sky-tests


  endless-sky-x86:
    image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    working_dir: /endless-sky
    volumes:
      - '.:/endless-sky'
    command:
      - '/bin/bash'
      - '-c'
      - |
        mkdir -p build/steam-x86
        cd build/steam-x86
        cmake ../../ -GNinja -DES_STEAM_X86=ON -DES_RELEASE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-m32
        ninja EndlessSky EndlessSkyTests
        ./endless-sky --version
        ./endless-sky-tests
