services:
  steam-x64:
    image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    volumes:
      - '.:/endless-sky'
    working_dir: /endless-sky
    command:
      - '/bin/bash'
      - '-c'
      - |
        mkdir -p build/steam-x64
        cd build/steam-x64
        cmake ../../ -GNinja -DES_STEAM=ON -DES_VERSION_TYPE=release -DCMAKE_BUILD_TYPE=Release
        ninja


  steam-x86:
    image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    working_dir: /endless-sky
    volumes:
      - '.:/endless-sky'
    command:
      - '/bin/bash'
      - '-c'
      - |
        mkdir -p build/steam-x86
        cd build/steam-x86
        cmake ../../ -GNinja -DES_STEAM_X86=ON -DES_VERSION_TYPE=release -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-m32
        ninja


  test-steam-x64:
    image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    volumes:
      - '.:/endless-sky'
    working_dir: /endless-sky
    command:
      - '/bin/bash'
      - '-c'
      - |
        cd build/steam-x64
        ./endless-sky --version
        ctest --label-exclude benchmark


  test-steam-x86:
    image: registry.gitlab.steamos.cloud/steamrt/sniper/sdk:latest
    volumes:
      - '.:/endless-sky'
    working_dir: /endless-sky
    command:
      - '/bin/bash'
      - '-c'
      - |
        cd build/steam-x86
        ./endless-sky --version
        ctest --label-exclude benchmark
