name: Build MacOS
description: Builds and run the unit tests on MacOS
inputs:
  ccache:
    description: Whether to use ccache or not
    default: 'false'
  mavericks:
    description: Whether to build for MacOS 10.9 Mavericks
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install ccache
      if: ${{ inputs.ccache == 'true' }}
      run: brew install ccache
      shell: bash
    - uses: lukka/get-cmake@latest
    - uses: lukka/run-vcpkg@v10.2
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ inputs.maverics == 'true' && 'macos10.9' || 'macos' }}
        configurePresetCmdString: >
          [
          '--preset', '$[env.CONFIGURE_PRESET_NAME]',
          "${{ inputs.ccache == 'true' && '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache' || '' }}",
          '-DES_INCLUDE_HASH=ON',
          '-B', 'build/macos'
          ]
        buildPreset: ${{ inputs.mavericks == 'true' && 'macos10.9-release' || 'macos-release' }}
        buildPresetCmdString: >
          [
          '--build', 'build/macos',
          '--config', 'Release',
          '-t', 'EndlessSky',
          '-t', 'EndlessSkyTests'
          ]
    - name: Run Unit Tests
      run: ./build/macos/Release/EndlessSkyTests
      shell: bash
