services:
  endless-sky-x64:
    build:
      context: .
      args:
        arch: amd64
    volumes:
      - '../.:/endless-sky'
    command:
      - '/bin/bash'
      - '-c'
      - |
        mkdir -p build/steam-x64
        cd build/steam-x64
        cmake ../../ -GNinja -DES_STEAM=ON -DES_RELEASE=ON -DCMAKE_BUILD_TYPE=Release
        ninja EndlessSky EndlessSkyTests
        ./endless-sky --version
        ./endless-sky-tests


  endless-sky-x86:
    build:
      context: .
      args:
        arch: i386
    volumes:
      - '../.:/endless-sky'
    command:
      - '/bin/bash'
      - '-c'
      - |
        mkdir -p build/steam-x86
        cd build/steam-x86
        cmake ../../ -GNinja -DES_STEAM=ON -DES_RELEASE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-m32 -DVCPKG_CXX_FLAGS=-m32
        ninja EndlessSky EndlessSkyTests
        ./endless-sky --version
        ./endless-sky-tests
