name: Install Development Dependencies
description: Install the correct dependencies to build the game
runs:
  using: 'composite'
  steps:
    - if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install -y --no-install-recommends libfuse2 libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libgles2-mesa-dev libwayland-dev libxkbcommon-dev libegl1-mesa-dev ccache
      shell: bash

    - if: runner.os == 'Windows'
      run: choco install ccache
      shell: bash

    - if: runner.os == 'macOS'
      run: brew install ccache
      shell: bash
