name: Build Windows
description: Builds and run the unit tests on Windows
inputs:
  ccache:
    description: Whether to use ccache or not
    default: 'false'
  version:
    description: The MinGW version.
    required: true
  arch:
    description: The MinGW arch flavor.
    default: 'x64'
runs:
  using: 'composite'
  steps:
    - name: Get MinGW
      uses: quyykk/get-winlibs-mingw@v1
      with:
        version: ${{ inputs.version }}
        arch: ${{ inputs.arch }}
    - name: Install ccache
      if: ${{ inputs.ccache == 'true' }}
      run: choco install ccache
      shell: bash
    - uses: lukka/get-cmake@latest
    - uses: lukka/run-vcpkg@v10
      with:
        appendedCacheKey: ${{ inputs.version }}-${{ inputs.arch }}
    - uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ inputs.arch == 'x64' && 'mingw' || 'mingw32' }}
        configurePresetCmdString: >
          [
          '--preset', '$[env.CONFIGURE_PRESET_NAME]',
          "${{ inputs.ccache == 'true' && '-DCMAKE_CXX_COMPILER_LAUNCHER=ccache' || '' }}",
          '-DES_INCLUDE_HASH=ON',
          '-B', 'build/mingw'
          ]
        buildPreset: ${{ inputs.arch == 'x64' && 'mingw-release' || 'mingw32-release' }}
        buildPresetCmdString: >
          [
          '--build', 'build/mingw',
          '--config', 'Release',
          '-t', 'EndlessSky',
          '-t', 'EndlessSkyTests'
          ]
        testPreset: 'mingw-test'
