name: Release CD

on:
  workflow_dispatch:

jobs:
  deploy_steam:
    name: Deploy Steam
    runs-on: ubuntu-latest
    # environment: steam
    steps:
    - uses: actions/checkout@v4
      with:
        show-progress: false
    - name: Upload Steam Data Depot
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.data }}
        path: |
          changelog
          copyright
          credits.txt
          icon.png
          keys.txt
          license.txt
          data/
          images/
          sounds/
    # - uses: game-ci/steam-deploy@v1
    #   with:
    #     appId: 404410
    #     buildDescription: canary-${{ github.sha }}
    #     username: ${{ secrets.STEAM_DEPLOY_UN }}
    #     password: ${{ secrets.STEAM_DEPLOY_PW }}
    #     configVdf: ${{ secrets.STEAM_DEPLOY_VDF }}
    #     ssfnFileName: ${{ secrets.STEAM_DEPLOY_SSFN_NAME }}
    #     ssfnFileContents: ${{ secrets.STEAM_DEPLOY_SSFN }}
    #     rootPath: ''
    #     depot1Path: ${{ env.data }}
    #     depot3Path: ${{ env.win32 }}
    #     depot4Path: ${{ env.win64 }}
    #     depot5Path: ${{ env.macos }}
    #     depot6Path: ${{ env.linux32 }}
    #     depot7Path: ${{ env.linux64 }}
    #     releaseBranch: canary
