name: Publish

on:
  release:
    types:
      - published
  push:
    branches:
      - flatpak

jobs:
  flathub:
    name: Flathub
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v3
      - name: Install docker
        if: ${{ matrix.arch == 'aarch64' }}
        run: dnf -y install docker
      - name: Setup QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: endless-sky.flatpak
          manifest-path: io.github.endless_sky.endless_sky.json
          cache: false
          arch: ${{ matrix.arch }}
      # - uses: flatpak/flatpak-github-actions/flat-manager@v5
      #   name: Deploy
      #   with:
      #     repository: elementary
      #     flat-manager-url: https://hub.flathub.org/
      #     token: ${{ secrets.FLATHUB_TOKEN }}
