name: Steam

on:
  push:
    branches:
      - master
      - cmake
      - releases/v[0-9]+.[0-9]+.[0-9]+

jobs:
  changed:
    uses: ./.github/workflows/compute-changes.yml

  build_linux:
    name: Steam Linux
    needs: changed
    if: ${{ needs.changed.outputs.game_code == 'true' || needs.changed_outputs.cmake == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, x86]
    env:
      ARTIFACT: endless-sky
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build Endless Sky
      run: |
        cd steam
        docker-compose up endless-sky-${{ matrix.arch }} --build
    - name: Prepare binary
      run: cp build/steam-${{ matrix.arch }}/${{ env.ARTIFACT }} .
    - name: Upload GH artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary-${{ runner.os }}-${{ matrix.arch }}
        path: |
          ${{ env.ARTIFACT }}
          credits.txt


  test_linux:
    needs: build_linux
    if: ${{ needs.changed.outputs.game_code == 'true' || needs.changed.outputs.cmake == 'true' || needs.changed.integration_tests == 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    env:
      snapshot: latest-steam-client-general-availability
      tarball: steam-runtime.tar.xz
    steps:
    - uses: actions/checkout@v3
    - name: Download Steam Runtime environment
      run: curl -sSf https://repo.steampowered.com/steamrt-images-scout/snapshots/${{ env.snapshot }}/${{ env.tarball }} > ${{ env.tarball }}
    - name: Extract Steam Runtime
      run: tar -xf ${{ env.tarball }}
    - name: Download Endless Sky binary
      uses: actions/download-artifact@v3
      with:
        name: binary-${{ runner.os }}-x64
        path: .
    - name: Install xvfb runtime dependencies
      run: |
        sudo apt-get update -q
        sudo apt-get install -y --no-install-recommends libosmesa6 mesa-utils
    - name: Pin Steam libraries
      run: steam-runtime/setup.sh
    - run: chmod +x endless-sky
    - run: steam-runtime/run.sh ./endless-sky -v
    - name: Execute data parsing test
      run: steam-runtime/run.sh ./utils/test_parse.sh ./endless-sky
    # NOTE: As with the non-Steam integration tests, on Ubuntu 18.04 the call to SDL_GL_CreateContext fails
    # with SDL error "Could not create GL Context: BadValue (integer parameter out of range for operation)"
    - name: Execute integration tests
      if: matrix.os != 'ubuntu-18.04'
      env:
          PRINT_GLXINFO: true
      run: steam-runtime/run.sh tests/integration/run_tests_headless.sh
